// Per-provider fan-out for installed skills.
//
// We physically COPY the managed skill folder into each enabled provider's
// location. Symlinks were rejected up front (architecture critique A7/A8 —
// OneDrive-synced %USERPROFILE% paths on Windows can render symlinks as
// `EACCES`/`EBUSY`). Plain copies survive that hostile environment with the
// trade-off of using more disk.
//
// Atomicity: write into a sibling `<name>.tmp-<rand>/` then `fs.rename` it
// onto the final per-provider path. The rename is atomic on the same volume,
// so if Electron is killed mid-copy we never leave a half-written skill at
// the live target. If the rename fails (cross-volume, EXDEV), we fall back
// to remove-then-copyDirRecursive into place.
//
// Idempotency: if the live target already exists with the same content hash
// we no-op. If it exists with a *different* hash and `force: false`, we fail
// with a clear error so the user can resolve manually (a hand-edited skill
// in `~/.claude/skills/<name>/` shouldn't be silently clobbered).

import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import { copyDirRecursive, rehashManagedFolder } from './ingestion';
import type { FanoutResult, ProviderTarget, Skill, SkillFrontmatter } from './types';

export interface ApplyFanoutOptions {
  force?: boolean;
}

/**
 * Resolve the per-provider directory each target writes to. All paths live
 * under the OS user home. We never inject `<userData>/` here — these are the
 * provider-native locations CLIs scan on startup.
 */
export function targetDirFor(provider: ProviderTarget, skillName: string): string {
  const home = os.homedir();
  switch (provider) {
    case 'claude':
      return path.join(home, '.claude', 'skills', skillName);
    case 'codex':
      return path.join(home, '.codex', 'skills', skillName);
    case 'gemini':
      // Gemini's extension layout is keyed off a unique extension dir name;
      // we namespace with `sigmalink-` so the user can recognise managed copies.
      return path.join(home, '.gemini', 'extensions', `sigmalink-${skillName}`);
    default: {
      const exhaustive: never = provider;
      throw new Error(`Unknown provider target: ${String(exhaustive)}`);
    }
  }
}

/**
 * Write a Gemini extension scaffold into `destDir` from the managed skill
 * folder. The Gemini CLI looks for `gemini-extension.json` + a `commands/`
 * directory containing TOML files — we synthesise both from the SKILL.md
 * frontmatter + body.
 */
function writeGeminiExtension(
  managedSkillDir: string,
  destDir: string,
  fm: SkillFrontmatter,
  body: string,
): void {
  fs.mkdirSync(destDir, { recursive: true });
  // Copy the original SKILL.md alongside so the user can inspect it and
  // future migrations have the canonical source.
  copyDirRecursive(managedSkillDir, destDir);

  const manifest = {
    name: `sigmalink-${fm.name}`,
    version: fm.version ?? '0.0.0',
    description: fm.description,
    contextFileName: 'SKILL.md',
  };
  fs.writeFileSync(
    path.join(destDir, 'gemini-extension.json'),
    JSON.stringify(manifest, null, 2),
    'utf8',
  );

  // Synthesize a minimal `commands/<name>.toml` that wraps the SKILL.md body
  // as a slash-command. The Gemini extension format keys off TOML so we keep
  // this conservative — embed the body verbatim and let the user trigger it.
  const commandsDir = path.join(destDir, 'commands');
  fs.mkdirSync(commandsDir, { recursive: true });
  const tomlPath = path.join(commandsDir, `${fm.name}.toml`);
  const tomlBody = body.replace(/"""/g, '"\\""\\""'); // defang triple-quotes
  const toml =
    `# Auto-generated by SigmaLink. Do not edit; re-run skill fan-out instead.\n` +
    `description = ${JSON.stringify(fm.description)}\n` +
    `prompt = """\n${tomlBody}\n"""\n`;
  fs.writeFileSync(tomlPath, toml, 'utf8');
}

function safeRimraf(target: string): void {
  try {
    fs.rmSync(target, { recursive: true, force: true });
  } catch {
    /* best-effort */
  }
}

/**
 * Atomically replace `targetDir` with the contents of `stagedDir` (a temp
 * directory on the same volume). Falls back to a delete + recursive copy if
 * the rename trips EXDEV / EBUSY (Windows OneDrive lock symptoms).
 */
function commitStaged(stagedDir: string, targetDir: string): void {
  fs.mkdirSync(path.dirname(targetDir), { recursive: true });
  if (fs.existsSync(targetDir)) safeRimraf(targetDir);
  try {
    fs.renameSync(stagedDir, targetDir);
    return;
  } catch (err) {
    // Cross-volume or sync-lock: fall back to a recursive copy then remove.
    void err;
  }
  copyDirRecursive(stagedDir, targetDir);
  safeRimraf(stagedDir);
}

/**
 * Apply fan-out for a single skill onto the supplied provider targets.
 *
 * Returns one `FanoutResult` per provider. A failure for one provider does
 * not stop the others — the caller (`SkillsManager`) records which providers
 * are now in error state.
 */
export async function applyFanout(
  skill: Skill,
  managedSkillDir: string,
  fm: SkillFrontmatter,
  body: string,
  targets: ProviderTarget[],
  opts: ApplyFanoutOptions = {},
): Promise<FanoutResult[]> {
  const results: FanoutResult[] = [];

  // Verify the managed source still matches the recorded hash before fan-out.
  // This protects against silently shipping out-of-date copies if the managed
  // tree has been edited under the user.
  let managedHash = '';
  try {
    managedHash = rehashManagedFolder(managedSkillDir);
  } catch {
    /* will be reflected in the per-target failures below */
  }
  if (skill.contentHash && managedHash && managedHash !== skill.contentHash) {
    // Continue with fan-out anyway but record the drift in each result.
    // The manager will surface a UI badge.
  }

  for (const provider of targets) {
    const targetDir = targetDirFor(provider, skill.name);
    try {
      // Idempotency: if the target already matches the managed hash, no-op.
      if (fs.existsSync(targetDir)) {
        const existingHash = (() => {
          try {
            return rehashManagedFolder(targetDir);
          } catch {
            return null;
          }
        })();
        if (existingHash === skill.contentHash) {
          results.push({ provider, ok: true, targetPath: targetDir });
          continue;
        }
        if (existingHash && existingHash !== skill.contentHash && !opts.force) {
          throw new Error(
            `Refusing to overwrite ${targetDir}: existing copy has a different content hash. ` +
              `Delete it manually or pass force=true.`,
          );
        }
      }

      const stageRoot = path.join(
        path.dirname(targetDir),
        `.sigmalink-stage-${skill.name}-${crypto.randomBytes(4).toString('hex')}`,
      );
      try {
        if (provider === 'gemini') {
          writeGeminiExtension(managedSkillDir, stageRoot, fm, body);
        } else {
          // Claude / Codex both want the bare skill folder.
          copyDirRecursive(managedSkillDir, stageRoot);
        }
        commitStaged(stageRoot, targetDir);
      } catch (err) {
        safeRimraf(stageRoot);
        throw err;
      }

      results.push({ provider, ok: true, targetPath: targetDir });
    } catch (err) {
      results.push({
        provider,
        ok: false,
        targetPath: targetDir,
        error: err instanceof Error ? err.message : String(err),
      });
    }
  }

  return results;
}

/**
 * Remove the fan-out copy for a single provider. Best-effort — failures are
 * logged but never thrown so an uninstall can still proceed across providers.
 */
export function removeFanout(provider: ProviderTarget, skillName: string): { ok: boolean; targetPath: string; error?: string } {
  const targetDir = targetDirFor(provider, skillName);
  if (!fs.existsSync(targetDir)) return { ok: true, targetPath: targetDir };
  try {
    fs.rmSync(targetDir, { recursive: true, force: true });
    return { ok: true, targetPath: targetDir };
  } catch (err) {
    return {
      ok: false,
      targetPath: targetDir,
      error: err instanceof Error ? err.message : String(err),
    };
  }
}
