// P6 FEAT-3 — usage ledger DAO.
//
// Reads/writes the `usage_ledger` table (migration 0029). Token/cost telemetry
// is harvested from the Claude CLI `result` envelope (total_cost_usd + usage{})
// at the assistant turn's success-finalize site (runClaudeCliTurn.trajectory.ts).
// Only the in-app assistant CLI turn path emits machine-readable usage, so rows
// are keyed by `conversationId` (the assistant has no agent_sessions row);
// `sessionId` stays NULL for those turns and is reserved for any future
// PTY-session source.
//
// Kept in a dependency-injected module (not inlined in rpc-router) because
// rpc-router pulls in Electron + better-sqlite3 and can't load under vitest. The
// DAO takes the drizzle handle as an argument so the test feeds a chainable fake.
//
// The INSERT uses the drizzle query builder; the two aggregate reads use raw
// `sql` templates run through the drizzle handle (`db.get` / `db.all`), mirroring
// the aggregation pattern in conversations.ts. weekSummary resolves a row's
// workspace via BOTH linkage paths (session_id → agent_sessions and
// conversation_id → conversations) so assistant-originated turns — the only
// priced source today — are attributed to the right workspace.

import { sql } from 'drizzle-orm';
import { usageLedger } from '../db/schema';
import type { getDb } from '../db/client';
import type {
  UsageSummary,
  UsageWeekSummary,
  UsageByProvider,
} from '../../../shared/types';

/** The drizzle DB handle, typed off the live `getDb` return (a test passes a
 *  chainable fake cast through this — better-sqlite3 can't load under vitest). */
export type UsageDb = ReturnType<typeof getDb>;

/** One recorded turn's usage, harvested from the Claude CLI result envelope. */
export interface RecordTurnInput {
  sessionId: string | null;
  conversationId: string | null;
  providerId: string;
  modelId: string | null;
  inputTokens: number;
  outputTokens: number;
  cacheCreationTokens: number;
  cacheReadTokens: number;
  totalCostUsd: number | null;
  recordedAt: number;
}

const EMPTY_SUMMARY: UsageSummary = {
  inputTokens: 0,
  outputTokens: 0,
  cacheCreationTokens: 0,
  cacheReadTokens: 0,
  totalCostUsd: null,
  turnCount: 0,
};

/** Coerce any value to a non-negative integer; missing/NaN → 0. Defensive: the
 *  CLI envelope's `usage{}` is `Record<string, unknown>`, so every field is
 *  treated as untrusted at the boundary. */
function intOf(value: unknown): number {
  const n = Math.trunc(Number(value));
  return Number.isFinite(n) && n > 0 ? n : 0;
}

/** Coerce to a finite number or null (cost is REAL/nullable). */
function costOf(value: unknown): number | null {
  if (value == null) return null;
  const n = Number(value);
  return Number.isFinite(n) ? n : null;
}

/**
 * Insert one turn's usage row. Every numeric field is hardened at the boundary
 * (intOf / costOf) so a malformed envelope can never write a NaN/negative. The
 * id is generated by the caller-free `crypto.randomUUID()` only when missing —
 * callers supply pre-coerced fields via {@link RecordTurnInput}, so this just
 * maps them onto the column shape.
 */
export function recordTurn(db: UsageDb, input: RecordTurnInput): void {
  db.insert(usageLedger)
    .values({
      id: crypto.randomUUID(),
      sessionId: input.sessionId,
      conversationId: input.conversationId,
      providerId: input.providerId,
      modelId: input.modelId,
      inputTokens: intOf(input.inputTokens),
      outputTokens: intOf(input.outputTokens),
      cacheCreationTokens: intOf(input.cacheCreationTokens),
      cacheReadTokens: intOf(input.cacheReadTokens),
      totalCostUsd: costOf(input.totalCostUsd),
      recordedAt: input.recordedAt,
    })
    .run();
}

interface SummaryRow {
  inputTokens: number | null;
  outputTokens: number | null;
  cacheCreationTokens: number | null;
  cacheReadTokens: number | null;
  totalCostUsd: number | null;
  turnCount: number | null;
}

/** Sum all turns for one session/pane. Empty (zeros / null cost) when no turn
 *  has been recorded for the session — the common case, since only assistant
 *  conversations (not pane sessions) produce usage today. */
export function sessionSummary(db: UsageDb, sessionId: string): UsageSummary {
  const row = db.get<SummaryRow>(sql`
    SELECT
      COALESCE(SUM(input_tokens), 0)          AS inputTokens,
      COALESCE(SUM(output_tokens), 0)         AS outputTokens,
      COALESCE(SUM(cache_creation_tokens), 0) AS cacheCreationTokens,
      COALESCE(SUM(cache_read_tokens), 0)     AS cacheReadTokens,
      SUM(total_cost_usd)                     AS totalCostUsd,
      COUNT(*)                                AS turnCount
    FROM usage_ledger
    WHERE session_id = ${sessionId}
  `);
  if (!row) return { ...EMPTY_SUMMARY };
  return {
    inputTokens: intOf(row.inputTokens),
    outputTokens: intOf(row.outputTokens),
    cacheCreationTokens: intOf(row.cacheCreationTokens),
    cacheReadTokens: intOf(row.cacheReadTokens),
    totalCostUsd: costOf(row.totalCostUsd),
    turnCount: intOf(row.turnCount),
  };
}

interface ByProviderRow {
  providerId: string;
  totalCostUsd: number | null;
  inputTokens: number | null;
  outputTokens: number | null;
  turnCount: number | null;
}

/**
 * Week-to-date spend for a workspace, grouped by provider. A ledger row belongs
 * to the workspace if EITHER linkage resolves to it:
 *   - session_id      → agent_sessions.workspace_id  (future PTY-session source)
 *   - conversation_id → conversations.workspace_id   (assistant turns — today's
 *                                                      only priced source)
 * Rows older than `sinceMs` are excluded by the index-backed recorded_at filter.
 */
export function weekSummary(
  db: UsageDb,
  workspaceId: string,
  sinceMs: number,
): UsageWeekSummary {
  const rows = db.all<ByProviderRow>(sql`
    SELECT
      u.provider_id                       AS providerId,
      SUM(u.total_cost_usd)               AS totalCostUsd,
      COALESCE(SUM(u.input_tokens), 0)    AS inputTokens,
      COALESCE(SUM(u.output_tokens), 0)   AS outputTokens,
      COUNT(*)                            AS turnCount
    FROM usage_ledger u
    LEFT JOIN agent_sessions s ON s.id = u.session_id
    LEFT JOIN conversations  c ON c.id = u.conversation_id
    WHERE u.recorded_at >= ${sinceMs}
      AND (s.workspace_id = ${workspaceId} OR c.workspace_id = ${workspaceId})
    GROUP BY u.provider_id
    ORDER BY SUM(u.total_cost_usd) DESC, u.provider_id ASC
  `);
  const byProvider: UsageByProvider[] = (rows ?? []).map((r) => ({
    providerId: r.providerId,
    totalCostUsd: costOf(r.totalCostUsd),
    inputTokens: intOf(r.inputTokens),
    outputTokens: intOf(r.outputTokens),
    turnCount: intOf(r.turnCount),
  }));
  return { weekStartMs: sinceMs, byProvider };
}
