import fs from 'node:fs';
import path from 'node:path';
import { buildCapsuleText, type PlanCapsule } from '@/shared/plan-capsule';
// Audit 2026-06-10 — containment keystone (pure node, fail-closed; see
// core/security/path-guard.ts). briefPane judges the renderer-supplied
// worktreePath against the injected allowed roots BEFORE any disk write.
import { assertAllowedPath } from '../security/path-guard';

const SCOPE_BLOCK_START = '<!-- sigmalink-scope:start -->';
const SCOPE_BLOCK_END = '<!-- sigmalink-scope:end -->';

function buildScopeBlockContent(worktreePath: string, capsule: PlanCapsule): string {
  const lines: string[] = [
    SCOPE_BLOCK_START,
    `## Scope guidance (auto-generated by SigmaLink)`,
    ``,
    `Worktree: \`${worktreePath}\``,
    ``,
    `**Do NOT write outside this worktree.**`,
  ];

  if (capsule.outOfScope.length > 0) {
    lines.push(``, `**Out of scope paths:**`);
    for (const o of capsule.outOfScope) {
      lines.push(`- ${o}`);
    }
  }

  lines.push(``, SCOPE_BLOCK_END);
  return lines.join('\n');
}

function writeFileAtomic(target: string, content: string): void {
  const tmp = `${target}.${process.pid}.${Date.now()}.tmp`;
  fs.writeFileSync(tmp, content, 'utf8');
  fs.renameSync(tmp, target);
}

export async function writeScopeBlock(worktreePath: string, capsule: PlanCapsule): Promise<void> {
  const target = path.join(worktreePath, 'CLAUDE.md');
  const existing = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : '';

  const managedBlock = buildScopeBlockContent(worktreePath, capsule);

  const startIdx = existing.indexOf(SCOPE_BLOCK_START);
  const endIdx = existing.indexOf(SCOPE_BLOCK_END);

  if (startIdx !== -1 && endIdx !== -1 && endIdx > startIdx) {
    // Block already present — replace it.
    const before = existing.slice(0, startIdx);
    const after = existing.slice(endIdx + SCOPE_BLOCK_END.length);
    const next = before + managedBlock + after;
    if (next === existing) return; // already identical — skip write
    fs.mkdirSync(path.dirname(target), { recursive: true });
    writeFileAtomic(target, next);
    return;
  }

  // No markers present — append the block.
  const separator = existing.length > 0 && !existing.endsWith('\n\n') ? '\n\n' : '';
  const trailingNewline = existing.length > 0 && !existing.endsWith('\n') ? '\n' : '';
  const next =
    existing.length === 0
      ? managedBlock + '\n'
      : existing + trailingNewline + separator + managedBlock + '\n';
  if (next === existing) return;
  fs.mkdirSync(path.dirname(target), { recursive: true });
  writeFileAtomic(target, next);
}

/**
 * C-5 / audit 2026-06-10 — the `panes.brief` RPC body, extracted from
 * rpc-router so the containment guard is unit-testable (the router cannot
 * load under vitest). Order matters: the containment check throws BEFORE the
 * CLAUDE.md write AND before the PTY capsule injection, so an out-of-roots
 * path produces no side effects at all ('path outside workspace').
 *
 * Sibling parity: git.worktreeCreate / git.openInPane / git.runCommand and
 * the fs.* controller all contain renderer paths the same way.
 */
export async function briefPane(
  input: { sessionId: string; worktreePath: string | null; capsule: PlanCapsule },
  deps: {
    /** Authoritative allowed-roots provider (rpc-router's fsAllowedRoots). */
    allowedRoots: () => string[];
    /** PTY write sink — (sessionId, data). */
    writePty: (sessionId: string, data: string) => void;
  },
): Promise<void> {
  if (input.worktreePath) {
    const safe = assertAllowedPath(input.worktreePath, deps.allowedRoots());
    await writeScopeBlock(safe, input.capsule);
  }
  deps.writePty(input.sessionId, buildCapsuleText(input.capsule) + '\n');
}
