import fs from 'node:fs';
import path from 'node:path';
import type { PlanCapsule } from '@/shared/plan-capsule';

const SCOPE_BLOCK_START = '<!-- sigmalink-scope:start -->';
const SCOPE_BLOCK_END = '<!-- sigmalink-scope:end -->';

function buildScopeBlockContent(worktreePath: string, capsule: PlanCapsule): string {
  const lines: string[] = [
    SCOPE_BLOCK_START,
    `## Scope guidance (auto-generated by SigmaLink)`,
    ``,
    `Worktree: \`${worktreePath}\``,
    ``,
    `**Do NOT write outside this worktree.**`,
  ];

  if (capsule.outOfScope.length > 0) {
    lines.push(``, `**Out of scope paths:**`);
    for (const o of capsule.outOfScope) {
      lines.push(`- ${o}`);
    }
  }

  lines.push(``, SCOPE_BLOCK_END);
  return lines.join('\n');
}

function writeFileAtomic(target: string, content: string): void {
  const tmp = `${target}.${process.pid}.${Date.now()}.tmp`;
  fs.writeFileSync(tmp, content, 'utf8');
  fs.renameSync(tmp, target);
}

export async function writeScopeBlock(worktreePath: string, capsule: PlanCapsule): Promise<void> {
  const target = path.join(worktreePath, 'CLAUDE.md');
  const existing = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : '';

  const managedBlock = buildScopeBlockContent(worktreePath, capsule);

  const startIdx = existing.indexOf(SCOPE_BLOCK_START);
  const endIdx = existing.indexOf(SCOPE_BLOCK_END);

  if (startIdx !== -1 && endIdx !== -1 && endIdx > startIdx) {
    // Block already present — replace it.
    const before = existing.slice(0, startIdx);
    const after = existing.slice(endIdx + SCOPE_BLOCK_END.length);
    const next = before + managedBlock + after;
    if (next === existing) return; // already identical — skip write
    fs.mkdirSync(path.dirname(target), { recursive: true });
    writeFileAtomic(target, next);
    return;
  }

  // No markers present — append the block.
  const separator = existing.length > 0 && !existing.endsWith('\n\n') ? '\n\n' : '';
  const trailingNewline = existing.length > 0 && !existing.endsWith('\n') ? '\n' : '';
  const next =
    existing.length === 0
      ? managedBlock + '\n'
      : existing + trailingNewline + separator + managedBlock + '\n';
  if (next === existing) return;
  fs.mkdirSync(path.dirname(target), { recursive: true });
  writeFileAtomic(target, next);
}
